/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AuthButtons() {
  return (
    <div className="flex gap-5 leading-6">
      <button className="px-4 py-2 rounded-md border border-solid border-slate-500 text-slate-900">
        Login
      </button>
      <button className="px-4 py-2 text-white rounded-md bg-orange-600">
        Register
      </button>
    </div>
  );
}

export default AuthButtons;
