/**
 * This code was generated by Builder.io.
 */
import React from "react";

function BlogCard() {
  return (
    <article className="flex flex-col items-center pb-20 ml-12 max-w-full text-base rounded-3xl border border-black border-solid shadow-sm bg-orange-300 bg-opacity-10 w-[486px] max-md:mt-10">
      <div className="flex relative flex-col items-start self-stretch px-3 pt-20 pb-4 w-full text-xs leading-5 text-gray-500 rounded-3xl min-h-[254px] max-md:pr-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/067ba0be977ed9cc7f0b79278138fad895afd134f84cfe94241a36a41c000ece?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
          alt="Blog post cover"
          className="object-cover absolute inset-0 size-full"
        />
        <time
          dateTime="2024-02-12"
          className="relative px-3.5 py-3 mt-32 rounded-3xl bg-zinc-300 max-md:mt-10"
        >
          12 Feb 2024
        </time>
      </div>
      <h2 className="px-16 py-4 mt-3.5 max-w-full tracking-normal text-center text-white whitespace-nowrap rounded-3xl bg-orange-600 bg-opacity-50 leading-[150%] w-[441px] max-md:px-5">
        azsdfgbvcxsaSDVBNGFEWQWFBN
      </h2>
      <p className="mt-6 mb-16 italic leading-6 text-black max-md:mb-10">
        aqw23e45rtyhbvcxsaq23567ujhbvcdsw23456y7hubgvcd
      </p>
    </article>
  );
}

export default BlogCard;
