/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import AuthButtons from "./AuthButtons";

function Header() {
  return (
    <header className="flex gap-5 justify-between w-full text-sm whitespace-nowrap max-md:flex-wrap max-md:max-w-full">
      <Logo />
      <Navigation />
      <AuthButtons />
    </header>
  );
}

export default Header;
