/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <div className="flex text-lg font-semibold leading-7 text-black">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a2a04250cd6a78e6f82bb5d6f144579998b5823bebb67e4f0dbeb3e0c583d37d?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
        alt="BlogApp Logo"
        className="shrink-0 aspect-[1.25] w-[50px]"
      />
      <div className="my-auto">BlogApp</div>
    </div>
  );
}

export default Logo;
