/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Navigation() {
  const navItems = ["Blogs", "About", "Product"];

  return (
    <nav className="flex gap-5 self-start mt-1 leading-[143%] text-slate-900">
      {navItems.map((item) => (
        <a
          key={item}
          href={`#${item.toLowerCase()}`}
          className="px-4 py-2 bg-white"
        >
          {item}
        </a>
      ))}
    </nav>
  );
}

export default Navigation;
